# Generated by Django 4.0.3 on 2022-03-30 02:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callNum', '0002_number_stamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnspotNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onspot_num', models.IntegerField(default=0)),
                ('onspot_stamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.AlterField(
            model_name='number',
            name='stamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
